[31;1mERROR[0m:
  [31mÃ—[0m You registered a constructor that returns a `Result`, but you
  [31mâ”‚[0m did not register an error handler for it. If I don't have an
  [31mâ”‚[0m error handler, I don't know what to do with the error when the
  [31mâ”‚[0m constructor fails!
  [31mâ”‚[0m
  [31mâ”‚[0m     â•­â”€[[36;1;4mquickstart/project/app/src/user_agent.rs[0m:13:1]
  [31mâ”‚[0m  [2m13[0m â”‚     impl UserAgent {
  [31mâ”‚[0m  [2m14[0m â”‚ [35;1mâ•­[0m[35;1mâ”€[0m[35;1mâ–¶[0m     #[request_scoped]
  [31mâ”‚[0m  [2m15[0m â”‚ [35;1mâ”œ[0m[35;1mâ”€[0m[35;1mâ–¶[0m     pub fn extract(request_head: &RequestHead) -> Result<Self, ToStrError> {
  [31mâ”‚[0m     Â· [35;1mâ•°[0m[35;1mâ”€â”€â”€[0m[35;1mâ”€[0m [35;1mThe fallible constructor was registered here[0m
  [31mâ”‚[0m  [2m16[0m â”‚             let Some(user_agent) = request_head.headers.get(USER_AGENT) else {
  [31mâ”‚[0m     â•°â”€â”€â”€â”€
  [31mâ”‚[0m   [36mhelp:[0m Add an error handler via `.error_handler`

note: Rerun with `PAVEX_DEBUG=true` to display more error details.